bibcite_export.settings:
  type: config_object
  label: 'Common export settings'
  mapping:
    show_full:
      type: boolean
      label: 'Show export links on full view'
    show_citation:
      type: boolean
      label: 'Show export links on citation view'
